import RAPIER from './node_modules/@dimforge/rapier3d/exports.js';
const world = new RAPIER.World({ x: 0, y: 0, z: 0 });
const gb = world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(32, -0.06, 32));
world.createCollider(RAPIER.ColliderDesc.cuboid(32, 0.05, 32), gb);
const pb = world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(32, 1.05, 32));
world.createCollider(RAPIER.ColliderDesc.capsule(0.7, 0.35), pb);
const c = world.intersectionWithShape({ x: 32, y: 1.05, z: 32 }, new RAPIER.Quaternion(0, 0, 0, 1), new RAPIER.Capsule(0.7, 0.35), undefined, undefined, undefined, pb);
console.log('probe-at-own-position (expect null):', c);
const c2 = world.intersectionWithShape({ x: 33, y: 1.05, z: 32 }, new RAPIER.Quaternion(0, 0, 0, 1), new RAPIER.Capsule(0.7, 0.35), undefined, undefined, undefined, pb);
console.log('probe-1m-away (expect null):', c2);
const c3 = world.intersectionWithShape({ x: 35, y: 1.05, z: 32 }, new RAPIER.Quaternion(0, 0, 0, 1), new RAPIER.Capsule(0.7, 0.35), undefined, undefined, undefined, pb);
console.log('probe-3m-away (expect null):', c3);
